import { readFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";

/**
 * The rules that keep the product usable on a small screen and readable in
 * both themes.
 *
 * Every one of these is a bug that was actually shipped, and every one is
 * invisible until someone opens the right page at the right width in the right
 * mode. A unit test cannot lay out a page, but it can hold the handful of
 * decisions that made the layout wrong in the first place.
 */

const root = process.cwd();
const css = readFileSync(resolve(root, "app/globals.css"), "utf8");

function walk(dir: string, out: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    if (entry === "node_modules" || entry === ".next") continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) walk(full, out);
    else if (full.endsWith(".tsx")) out.push(full);
  }
  return out;
}

const components = walk(resolve(root, "components")).concat(
  walk(resolve(root, "app")),
);

const relative = (file: string) =>
  file.replace(root, "").replace(/\\/g, "/").slice(1);

/** The two declarations of a token, light block then dark block. */
function tokenPair(name: string): [string, string] {
  const matches = [...css.matchAll(new RegExp(`--${name}:\\s*([^;]+);`, "g"))].map(
    (match) => match[1]!.trim(),
  );
  expect(matches.length, `--${name} should be declared twice`).toBeGreaterThanOrEqual(2);
  return [matches[0]!, matches[1]!];
}

describe("every token inverts", () => {
  it("includes --paper, which used to be white in both modes", () => {
    // `text-paper` means "ink on a dark fill". In dark mode the dark fill is
    // white, so the ink has to be black. While this was white in both, four
    // components rendered white on white and three of them had been patched
    // by hand with their own `dark:` overrides.
    const [light, dark] = tokenPair("paper");
    expect(light).not.toBe(dark);
  });

  it("includes the grounds and the ink", () => {
    for (const token of ["background", "foreground", "surface", "surface-muted"]) {
      const [light, dark] = tokenPair(token);
      expect(light, `--${token} does not invert`).not.toBe(dark);
    }
  });

  it("no longer needs a dark override to fix a filled button", () => {
    // `bg-brand-fill` + `text-brand-fill-foreground` invert together, so a
    // filled button needs no per-mode patch. A `dark:bg-*` next to a
    // `bg-forest` is the signature of the bug this replaced.
    for (const file of components) {
      const source = readFileSync(file, "utf8");
      expect(
        /bg-forest[^"]*dark:bg-/.test(source),
        `${relative(file)} patches a fill by hand`,
      ).toBe(false);
    }
  });
});

describe("utilities that components ask for actually exist", () => {
  it("generates surface-muted and the field colours", () => {
    // These were referenced by thirty-seven call sites and generated by none:
    // hover states did nothing and inputs had no background of their own.
    for (const name of [
      "--color-surface-muted",
      "--color-field-background",
      "--color-field-foreground",
    ]) {
      expect(css, `${name} is not generated`).toContain(name);
    }
  });

  it("defines prose-vu, which renders every post and comment body", () => {
    // Four components asked for it and it did not exist, so member markdown
    // had no styling and a pasted URL widened the card past the screen.
    expect(css).toContain(".prose-vu");
    expect(css).toMatch(/\.prose-vu\s*\{[^}]*overflow-wrap:\s*anywhere/);
  });
});

describe("layout holds at 320px", () => {
  it("gives every responsive grid a base column count", () => {
    // A grid with no `grid-template-columns` gets one implicit `auto` column,
    // and `auto` is content-sized: one long name and the column grows past the
    // screen. This was the last real overflow left on the space members tab.
    const offenders: string[] = [];
    for (const file of components) {
      const source = readFileSync(file, "utf8");
      for (const match of source.matchAll(/"grid[^"]*"/g)) {
        const value = match[0];
        const responsive = /(sm|md|lg|xl):grid-cols-/.test(value);
        const base = /(?:^|\s)grid-cols-/.test(value.replace(/(sm|md|lg|xl):grid-cols-\S+/g, ""));
        if (responsive && !base) offenders.push(`${relative(file)}: ${value}`);
      }
    }
    expect(offenders).toEqual([]);
  });

  it("measures the viewport with dvh where a pane fills the screen", () => {
    // 100vh does not account for the browser chrome on iOS, so a pane sized
    // that way pushes its composer below the fold.
    const offenders: string[] = [];
    for (const file of components) {
      const source = readFileSync(file, "utf8");
      if (/h-\[calc\(100vh/.test(source)) offenders.push(relative(file));
    }
    expect(offenders).toEqual([]);
  });

  it("keeps every member page inside the app frame", () => {
    // Settings and billing rendered with no header, no tab bar and no
    // horizontal padding: text sat flush against both screen edges with no
    // way to navigate away.
    for (const page of [
      "app/(member)/settings/page.tsx",
      "app/(member)/billing/page.tsx",
      "app/(member)/billing/delete/page.tsx",
      "app/(member)/billing/cancel/[id]/page.tsx",
    ]) {
      const source = readFileSync(resolve(root, page), "utf8");
      expect(source, `${page} is outside AppShell`).toContain("<AppShell>");
    }
  });
});

describe("the theme control lives in the navbar", () => {
  it("is in the header", () => {
    const header = readFileSync(
      resolve(root, "components/app/app-header.tsx"),
      "utf8",
    );
    expect(header).toContain("ThemeToggle");
  });

  it("no longer floats over the feed", () => {
    // The floating control sat on the fourth cell of the post action bar at
    // 320px and was the only chrome that moved with the page.
    expect(existsSync(resolve(root, "components/app/theme-fab.tsx"))).toBe(false);
    const shell = readFileSync(resolve(root, "components/app/app-shell.tsx"), "utf8");
    expect(shell).not.toContain("ThemeFab");
  });
});

describe("a phone shows media in place", () => {
  it("never opens the lightbox on a small screen", () => {
    // An overlay that covers the whole screen hides the post it belongs to and
    // costs a second gesture to leave. Guarded at the component itself so no
    // future caller can reintroduce it.
    const modal = readFileSync(
      resolve(root, "components/feed/post-gallery-modal.tsx"),
      "utf8",
    );
    expect(modal).toContain("useIsMobile");
    expect(modal).toMatch(/if \(isMobile \|\|/);
  });

  it("plays video where it sits, at every width", () => {
    const media = readFileSync(resolve(root, "components/feed/post-media.tsx"), "utf8");
    expect(media).toContain("InlineVideo");
    const inline = readFileSync(
      resolve(root, "components/feed/inline-video.tsx"),
      "utf8",
    );
    // A real player with real controls, not a poster that opens something.
    expect(inline).toMatch(/<video[\s\S]*?controls/);
    // The third-party embed only loads once someone asks for it.
    expect(inline).toMatch(/playing[\s\S]*?iframe/);
  });
});
