#!/usr/bin/env node
/**
 * Theme palettes: four colours in, every token the site paints with out.
 *
 * A member picks a palette in the app's Theme dialog (`data-accent` on
 * <html>), and it applies to the whole site: the landing and marketing pages,
 * the sign-in pages, the member app and the admin console (DEC-082, DEC-084).
 * Each palette is four colours, darkest to lightest, in
 * `lib/theme/palettes.json`. This script turns them into tokens for light
 * mode (an off-white page) and dark mode (black), for the app, for the app's
 * rails and hero band, and for the marketing site, and writes them into
 * `app/globals.css`:
 *
 *   - the default palette (palettes.json "default") into the marked
 *     `theme-default:*` regions inside the base blocks, so the site is in it
 *     with no attribute at all;
 *   - every other palette into the `theme-accents` block, keyed by
 *     `[data-accent="<id>"]`.
 *
 * Derivation: the palette's darkest colour is the app rail; `fill` picks the
 * colour that carries action in light mode, `darkFill` the one that carries it
 * on black (a light tint, labelled in the darkest), `wash` (optional) the pale
 * tint chips and the active row sit on. A palette may instead give explicit
 * token sets under `tokens` (Mulberry keeps its hand-tuned values that way).
 *
 * Every pair is held to WCAG before anything is written: derived colours
 * that miss are nudged (darker on a light ground, lighter on black) until
 * they clear, and explicit ones that miss stop the script. The grounds are
 * read from `globals.css` itself, so the two can never disagree.
 *
 *   node scripts/theme-accents.mjs           write the CSS
 *   node scripts/theme-accents.mjs --check   fail if the CSS is out of date
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(here, "..");
const CSS_PATH = resolve(ROOT, "app", "globals.css");
const PALETTES_PATH = resolve(ROOT, "lib", "theme", "palettes.json");

export const START = "/* theme-accents:start (generated by scripts/theme-accents.mjs; do not edit by hand) */";
export const END = "/* theme-accents:end */";

const SCOPE = ":has([data-app-shell], .vu-admin)";
const BANDS = ":is(.vu-app-sidebar, .vu-admin-rail, .vu-band)";

/** The base blocks, and the region inside each the default palette fills. */
export const SITE_LIGHT = ":root,\n  .light,\n  [data-theme=\"light\"] {";
export const SITE_DARK = ".dark,\n  [data-theme=\"dark\"] {";
export const APP_LIGHT = `:root${SCOPE} {`;
export const APP_DARK = `:root.dark${SCOPE} {`;
export const BAND_LIGHT = `:root${SCOPE} ${BANDS} {`;
export const BAND_DARK = `:root.dark${SCOPE} ${BANDS} {`;

const REGIONS = {
  "site-light": "    ",
  "site-dark": "    ",
  "app-light": "  ",
  "app-dark": "  ",
  "band-light": "  ",
  "band-dark": "  ",
};
const regionStart = (name) => `/* theme-default:${name}:start (generated; do not edit by hand) */`;
const regionEnd = (name) => `/* theme-default:${name}:end */`;

// ---------------------------------------------------------------- colour math

const toRgb = (hex) => {
  const v = hex.replace("#", "");
  return [0, 2, 4].map((i) => parseInt(v.slice(i, i + 2), 16));
};
const toHex = (rgb) =>
  "#" +
  rgb
    .map((c) => Math.max(0, Math.min(255, Math.round(c))).toString(16).padStart(2, "0"))
    .join("");
const lin = (c) => {
  const v = c / 255;
  return v <= 0.04045 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4;
};
const unlin = (c) => 255 * (c <= 0.0031308 ? c * 12.92 : 1.055 * c ** (1 / 2.4) - 0.055);

export const luminance = (hex) => {
  const [r, g, b] = toRgb(hex).map(lin);
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
};

export const contrast = (a, b) => {
  const [hi, lo] = [luminance(a), luminance(b)].sort((m, n) => n - m);
  return (hi + 0.05) / (lo + 0.05);
};

// OKLab, so a mix keeps its hue instead of greying through sRGB.
const toOklab = (hex) => {
  const [r, g, b] = toRgb(hex).map(lin);
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
  return [
    0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s,
    1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s,
    0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s,
  ];
};
const fromOklab = ([L, a, b]) => {
  const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3;
  return toHex(
    [
      4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
      -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
      -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
    ].map(unlin),
  );
};

/** `amount` of `b` mixed into `a`, in OKLab. */
export const mix = (a, b, amount) => {
  const A = toOklab(a);
  const B = toOklab(b);
  return fromOklab(A.map((v, i) => v + (B[i] - v) * amount));
};

const chroma = (hex) => {
  const [, a, b] = toOklab(hex);
  return Math.hypot(a, b);
};

const WHITE = "#ffffff";
const BLACK = "#000000";

/** Nudge `fg` toward `toward` until it clears `min` against `bg`. */
function clear(fg, bg, min, toward) {
  let out = fg;
  for (let step = 0; step < 80 && contrast(out, bg) < min; step += 1) out = mix(out, toward, 0.06);
  return out;
}

// ------------------------------------------------------------------ the CSS

const CR = String.fromCharCode(13);

/** `--name: #hex;` declarations in the block that opens with `opener`. */
export function tokensIn(css, opener) {
  const at = css.indexOf(opener);
  if (at === -1) throw new Error(`Block not found: ${opener}`);
  const open = css.indexOf("{", at);
  let depth = 0;
  let end = open;
  for (let i = open; i < css.length; i += 1) {
    if (css[i] === "{") depth += 1;
    else if (css[i] === "}") {
      depth -= 1;
      if (depth === 0) {
        end = i;
        break;
      }
    }
  }
  const tokens = {};
  for (const [, name, hex] of css.slice(open, end).matchAll(/--([a-z0-9-]+)\s*:\s*(#[0-9a-fA-F]{6})\s*;/g)) {
    tokens[name] = hex.toLowerCase();
  }
  return tokens;
}

export function readCss() {
  return readFileSync(CSS_PATH, "utf8").split(CR).join("");
}

export function readPalettes() {
  return JSON.parse(readFileSync(PALETTES_PATH, "utf8"));
}

/** The grounds the palettes sit on, as `globals.css` declares them. */
export function readBases(css = readCss()) {
  const appLight = tokensIn(css, APP_LIGHT);
  return {
    light: appLight,
    dark: { ...appLight, ...tokensIn(css, APP_DARK) },
    siteLight: tokensIn(css, SITE_LIGHT),
    siteDark: tokensIn(css, SITE_DARK),
  };
}

// --------------------------------------------------------------- derivation

function lightTokens(palette, base) {
  const { swatches, fill: fillIndex } = palette;
  const [c1, , c3, c4] = swatches;
  const F = swatches[fillIndex];
  const S = base.surface;
  const brandStrong = clear(mix(F, c1, 0.35), S, 7, BLACK);
  // The pale tint chips, badges and the active row sit on: the palette's
  // light end when it reads on the page (by lightness or by hue), otherwise a
  // pale tint of its mid colour. `wash` names one outright.
  let wash;
  if (palette.wash !== undefined) wash = swatches[palette.wash];
  else {
    wash = chroma(c4) > 0.035 ? c4 : mix(c4, WHITE, 0.25);
    if (contrast(wash, base.background) < 1.06 && chroma(wash) <= 0.035) wash = mix(c3, WHITE, 0.62);
  }
  // The app's primary button paints its fill with an 8% white sheen at the
  // top (the "Get Started" gradient), so its white label has to clear 4.5:1
  // there too, not only on the fill itself.
  let fill = clear(F, WHITE, 4.5, BLACK);
  for (let step = 0; step < 80 && contrast(mix(fill, WHITE, 0.08), WHITE) < 4.5; step += 1) {
    fill = mix(fill, BLACK, 0.04);
  }
  const hover = mix(fill, BLACK, 0.12);
  const tokens = {
    brand: clear(F, S, 3, BLACK),
    "brand-strong": brandStrong,
    "brand-wash": wash,
    "on-brand-wash": clear(c1, wash, 7, BLACK),
    "on-brand": WHITE,
    "brand-fill": fill,
    "brand-fill-hover": hover,
    "brand-fill-foreground": WHITE,
    primary: fill,
    "primary-foreground": WHITE,
    accent: fill,
    "accent-foreground": WHITE,
    focus: brandStrong,
    link: brandStrong,
    highlight: fill,
    "highlight-ink": brandStrong,
    "highlight-wash": wash,
    "on-highlight": WHITE,
    sidebar: c1,
    "sidebar-foreground": WHITE,
    "sidebar-accent": c4,
    "sidebar-accent-foreground": clear(c1, c4, 4.5, BLACK),
    "sidebar-border": mix(c1, BLACK, 0.28),
    "sidebar-ring": WHITE,
    forest: brandStrong,
    "deep-forest": mix(brandStrong, BLACK, 0.2),
    sage: wash,
    "cta-fill": fill,
    "cta-fill-hover": hover,
    "cta-fill-foreground": WHITE,
  };
  const bandFill = clear(mix(c1, WHITE, 0.13), WHITE, 4.5, BLACK);
  const muted = clear(mix(c4, WHITE, 0.35), bandFill, 4.5, WHITE);
  const band = {
    "foreground-muted": muted,
    olive: muted,
    "surface-muted": bandFill,
    default: bandFill,
    border: tokens["sidebar-border"],
    separator: tokens["sidebar-border"],
    "hairline-firm": mix(c1, WHITE, 0.24),
    "brand-fill": WHITE,
    "brand-fill-hover": c4,
    "brand-fill-foreground": clear(c1, c4, 4.5, BLACK),
    "on-highlight": c1,
    sage: c4,
    forest: c1,
  };
  return { tokens, band };
}

function darkTokens(palette, base) {
  const { swatches, darkFill, darkInk } = palette;
  const [c1, , c3, c4] = swatches;
  const S = base.surface;
  const pick = darkFill === "lift2" ? mix(c3, WHITE, 0.45) : swatches[darkFill];
  const fill = clear(pick, BLACK, 3.2, WHITE);
  const label = clear(c1, fill, 4.5, BLACK);
  // Brand text on black: the fill lifted, or, where the fill is close to the
  // body text's own white (Midnight's cream), the palette's blue lifted, so a
  // link still reads as a link.
  const brandStrong =
    darkInk === undefined
      ? clear(mix(fill, WHITE, 0.25), S, 7, WHITE)
      : clear(mix(swatches[darkInk], WHITE, 0.5), S, 7, WHITE);
  // A dark tint for chips. A darkest that is all but black gives no tint, so
  // the mid colour does instead.
  const wash = luminance(c1) < 0.01 ? mix(c3, BLACK, 0.45) : mix(c1, BLACK, 0.2);
  const sidebar = mix(c1, BLACK, 0.3);
  const hover = mix(fill, WHITE, 0.14);
  const tokens = {
    brand: clear(fill, S, 3, WHITE),
    "brand-strong": brandStrong,
    "brand-wash": wash,
    "on-brand-wash": clear(mix(c4, WHITE, 0.2), wash, 7, WHITE),
    "on-brand": label,
    "brand-fill": fill,
    "brand-fill-hover": hover,
    "brand-fill-foreground": label,
    primary: fill,
    "primary-foreground": label,
    accent: fill,
    "accent-foreground": label,
    focus: brandStrong,
    link: brandStrong,
    highlight: fill,
    "highlight-ink": brandStrong,
    "highlight-wash": wash,
    "on-highlight": label,
    sidebar,
    "sidebar-foreground": WHITE,
    "sidebar-accent": c4,
    "sidebar-accent-foreground": clear(c1, c4, 4.5, BLACK),
    // A rail on a black page needs an edge you can see.
    "sidebar-border": mix(sidebar, WHITE, 0.12),
    "sidebar-ring": WHITE,
    forest: brandStrong,
    "deep-forest": brandStrong,
    sage: wash,
    "cta-fill": fill,
    "cta-fill-hover": hover,
    "cta-fill-foreground": label,
  };
  const bandFill = clear(mix(sidebar, WHITE, 0.12), WHITE, 4.5, BLACK);
  const muted = clear(mix(c4, WHITE, 0.3), bandFill, 4.5, WHITE);
  const band = {
    "foreground-muted": muted,
    olive: muted,
    "surface-muted": bandFill,
    default: bandFill,
    border: tokens["sidebar-border"],
    separator: tokens["sidebar-border"],
    "hairline-firm": mix(sidebar, WHITE, 0.22),
    "brand-fill": WHITE,
    "brand-fill-hover": c4,
    "brand-fill-foreground": clear(c1, c4, 4.5, BLACK),
    "on-highlight": c1,
    sage: c4,
    forest: c1,
  };
  return { tokens, band };
}

/** The marketing site's brand roles, from the app's, for one mode. */
function siteTokens(app, mode, c1) {
  const t = app.tokens;
  if (mode === "light") {
    return {
      primary: t["brand-fill"],
      "primary-foreground": t["brand-fill-foreground"],
      accent: t["brand-fill"],
      "accent-foreground": t["brand-fill-foreground"],
      focus: t.brand,
      link: t["brand-strong"],
      success: t["brand-strong"],
      "success-foreground": WHITE,
      brand: t.brand,
      "brand-strong": t["brand-strong"],
      "brand-wash": t["brand-wash"],
      "on-brand-wash": t["on-brand-wash"],
      "on-brand": WHITE,
      "brand-fill": t["brand-fill"],
      "brand-fill-hover": t["brand-fill-hover"],
      "brand-fill-foreground": t["brand-fill-foreground"],
      "sidebar-accent": t["brand-wash"],
      "sidebar-accent-foreground": t["on-brand-wash"],
      "sidebar-ring": t.brand,
      forest: t["brand-strong"],
      "deep-forest": t["deep-forest"],
      sage: t["brand-wash"],
      "cta-fill": t["cta-fill"],
      "cta-fill-hover": t["cta-fill-hover"],
      "cta-fill-foreground": t["cta-fill-foreground"],
    };
  }
  // On black the accent is the palette's light ink, labelled in its darkest.
  const onInk = clear(c1, t["brand-strong"], 4.5, BLACK);
  return {
    primary: t["brand-fill"],
    "primary-foreground": t["brand-fill-foreground"],
    accent: t["brand-strong"],
    "accent-foreground": onInk,
    focus: t["brand-strong"],
    link: t["brand-strong"],
    success: t["brand-strong"],
    "success-foreground": onInk,
    brand: t.brand,
    "brand-strong": t["brand-strong"],
    "brand-wash": t["brand-wash"],
    "on-brand-wash": t["on-brand-wash"],
    "on-brand": t["on-brand"],
    "brand-fill": t["brand-fill"],
    "brand-fill-hover": t["brand-fill-hover"],
    "brand-fill-foreground": t["brand-fill-foreground"],
    "sidebar-accent": t["brand-wash"],
    "sidebar-accent-foreground": t["on-brand-wash"],
    "sidebar-ring": t["brand-strong"],
    forest: t["brand-strong"],
    "deep-forest": t.brand,
    sage: t["brand-wash"],
    "cta-fill": t["cta-fill"],
    "cta-fill-hover": t["cta-fill-hover"],
    "cta-fill-foreground": t["cta-fill-foreground"],
  };
}

/**
 * A palette's token sets: the app in light and dark (with the band in each),
 * and the marketing site in light and dark. Explicit sets win over derived.
 */
export function derivePalette(palette, bases) {
  const given = palette.tokens ?? {};
  const derivedLight = palette.fill === undefined ? null : lightTokens(palette, bases.light);
  const derivedDark = palette.darkFill === undefined ? null : darkTokens(palette, bases.dark);
  const light = {
    tokens: given.light ?? derivedLight?.tokens,
    band: given.bandLight ?? derivedLight?.band,
  };
  const dark = {
    tokens: given.dark ?? derivedDark?.tokens,
    band: given.bandDark ?? derivedDark?.band,
  };
  for (const [name, set] of [
    ["light", light.tokens],
    ["light band", light.band],
    ["dark", dark.tokens],
    ["dark band", dark.band],
  ]) {
    if (!set) throw new Error(`${palette.id}: no ${name} tokens (give fill/darkFill or explicit tokens)`);
  }
  return {
    light,
    dark,
    site: {
      light: given.siteLight ?? siteTokens(light, "light", palette.swatches[0]),
      dark: given.siteDark ?? siteTokens(dark, "dark", palette.swatches[0]),
    },
  };
}

// ---------------------------------------------------------------- contrast

/** What each palette must clear in the app, in each mode. */
export const ACCENT_PAIRS = [
  ["brand-strong", "surface", 4.5],
  ["on-brand-wash", "brand-wash", 4.5],
  ["brand", "surface", 3],
  ["brand-fill-foreground", "brand-fill", 4.5],
  ["link", "surface", 4.5],
  ["focus", "surface", 3],
  ["brand-fill", "background", 3],
  ["highlight-ink", "surface", 4.5],
  ["highlight-ink", "highlight-wash", 4.5],
  ["on-highlight", "highlight", 4.5],
  ["highlight-ink", "background", 4.5],
  ["sidebar-foreground", "sidebar", 4.5],
  ["sidebar-accent-foreground", "sidebar-accent", 4.5],
];

export const ACCENT_BAND_PAIRS = [
  ["foreground", "sidebar", 4.5],
  ["foreground-muted", "sidebar", 4.5],
  ["foreground", "surface-muted", 4.5],
  ["foreground-muted", "surface-muted", 4.5],
  ["brand-fill-foreground", "brand-fill", 4.5],
  ["brand", "sidebar", 3],
  ["sidebar-accent-foreground", "sidebar-accent", 4.5],
];

/** What each palette must clear on the marketing site, in each mode. */
export const SITE_PAIRS = [
  ["brand-strong", "surface", 4.5],
  ["on-brand-wash", "brand-wash", 4.5],
  ["brand", "surface", 3],
  ["brand-fill-foreground", "brand-fill", 4.5],
  ["link", "surface", 4.5],
  ["link", "background", 4.5],
  ["focus", "surface", 3],
  ["sidebar-accent-foreground", "sidebar-accent", 4.5],
  ["cta-fill-foreground", "cta-fill", 4.5],
  ["primary-foreground", "primary", 4.5],
  ["accent-foreground", "accent", 4.5],
  ["success-foreground", "success", 4.5],
];

/** Every failing pair, as readable lines. Empty when the palette passes. */
export function failures(id, derived, bases) {
  const out = [];
  const check = (scope, label, pairs) => {
    for (const [fg, bg, min] of pairs) {
      const r = contrast(scope[fg], scope[bg]);
      if (!(r >= min)) out.push(`${id} ${label}: ${fg} on ${bg} is ${r.toFixed(2)}:1 (needs ${min})`);
    }
  };
  for (const mode of ["light", "dark"]) {
    const scope = { ...bases[mode], ...derived[mode].tokens };
    check(scope, mode, ACCENT_PAIRS);
    check({ ...scope, foreground: WHITE, brand: WHITE, ...derived[mode].band }, `${mode} band`, ACCENT_BAND_PAIRS);
  }
  check({ ...bases.siteLight, ...derived.site.light }, "site light", SITE_PAIRS);
  check({ ...bases.siteDark, ...derived.site.dark }, "site dark", SITE_PAIRS);
  return out;
}

// ------------------------------------------------------------------ render

const declarations = (tokens, indent) =>
  Object.entries(tokens)
    .map(([name, value]) => `${indent}--${name}: ${value};`)
    .join("\n");

/** The default palette's six regions, keyed by region name. */
export function renderDefault(palette, bases) {
  const d = derivePalette(palette, bases);
  const sets = {
    "site-light": d.site.light,
    "site-dark": d.site.dark,
    "app-light": d.light.tokens,
    "app-dark": d.dark.tokens,
    "band-light": d.light.band,
    "band-dark": d.dark.band,
  };
  return Object.fromEntries(
    Object.entries(sets).map(([region, tokens]) => [region, declarations(tokens, REGIONS[region])]),
  );
}

/** Every other palette, keyed by `data-accent`, for the app and the site. */
export function renderAccents(palettes, bases, defaultId) {
  const parts = [START];
  for (const palette of palettes.filter((p) => p.id !== defaultId)) {
    const d = derivePalette(palette, bases);
    const id = palette.id;
    const site = `[data-accent="${id}"]`;
    parts.push(
      "",
      `/* ${palette.name}: ${palette.swatches.join(" ")} */`,
      `:root${site}${SCOPE} {\n${declarations(d.light.tokens, "  ")}\n}`,
      `:root.dark${site}${SCOPE} {\n${declarations(d.dark.tokens, "  ")}\n}`,
      `:root${site}${SCOPE} ${BANDS} {\n${declarations(d.light.band, "  ")}\n}`,
      `:root.dark${site}${SCOPE} ${BANDS} {\n${declarations(d.dark.band, "  ")}\n}`,
      // The marketing site's blocks live in the theme layer, like its base
      // blocks, so the app's unlayered blocks still win inside the app.
      `@layer theme {\n  :root${site} {\n${declarations(d.site.light, "    ")}\n  }\n\n` +
        `  :root.dark${site},\n  :root[data-theme="dark"]${site} {\n${declarations(d.site.dark, "    ")}\n  }\n}`,
    );
  }
  parts.push("", END);
  return parts.join("\n");
}

/** The stylesheet with a marked region's contents replaced. */
function withRegion(css, start, end, content, label) {
  const from = css.indexOf(start);
  const to = css.indexOf(end);
  if (from === -1 || to === -1 || to < from) throw new Error(`${label} markers not found in app/globals.css`);
  return css.slice(0, from) + content + css.slice(to + end.length);
}

/** The stylesheet with every generated region rewritten. */
export function render(css, data) {
  const bases = readBases(css);
  const byId = Object.fromEntries(data.palettes.map((p) => [p.id, p]));
  const fallback = byId[data.default];
  if (!fallback) throw new Error(`default palette "${data.default}" is not in palettes.json`);
  let next = css;
  const regions = renderDefault(fallback, bases);
  for (const [region, body] of Object.entries(regions)) {
    const start = regionStart(region);
    const end = regionEnd(region);
    const indent = REGIONS[region];
    next = withRegion(next, start, end, `${start}\n${body}\n${indent}${end}`, `theme-default:${region}`);
  }
  next = withRegion(next, START, END, renderAccents(data.palettes, bases, data.default), "theme-accents");
  return next;
}

// --------------------------------------------------------------------- main

function main() {
  const check = process.argv.includes("--check");
  const raw = readFileSync(CSS_PATH, "utf8");
  const crlf = raw.includes(CR + "\n");
  const css = raw.split(CR).join("");
  const data = readPalettes();
  const bases = readBases(css);

  const problems = data.palettes.flatMap((p) => failures(p.id, derivePalette(p, bases), bases));
  if (problems.length) {
    console.error(problems.join("\n"));
    console.error(`${problems.length} pair(s) fail; nothing written.`);
    process.exit(1);
  }

  const next = render(css, data);
  if (check) {
    if (next !== css) {
      console.error("app/globals.css is out of date: run node scripts/theme-accents.mjs");
      process.exit(1);
    }
    console.log("theme palettes are up to date");
    return;
  }
  writeFileSync(CSS_PATH, crlf ? next.split("\n").join(CR + "\n") : next);
  console.log(
    `wrote ${data.default} as the default and ${data.palettes.length - 1} palettes into app/globals.css`,
  );
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
