#!/usr/bin/env node
/**
 * Theme accents: one palette in, a full set of app tokens out.
 *
 * A member picks a palette in the app's Theme dialog (`data-accent` on
 * <html>). Each palette is four colours, darkest to lightest, in
 * `lib/theme/palettes.json`. This script turns them into the tokens the app
 * paints with, for light mode (an off-white page) and dark mode (black), and
 * for the rails and the hero band, and writes them into `app/globals.css`
 * between the `theme-accents` markers. The palette's darkest colour is the
 * rail; one of its middle colours carries action; its lightest is the tint
 * chips and the active row sit on.
 *
 * Every pair is held to the same thresholds as `scripts/check-theme-contrast.mjs`
 * before anything is written, and colours that miss are nudged (darker on a
 * light ground, lighter on black) until they clear. The grounds themselves are
 * read from the app blocks in `globals.css`, so the two can never disagree.
 *
 *   node scripts/theme-accents.mjs           write the block
 *   node scripts/theme-accents.mjs --check   fail if the block is out of date
 *
 * The built-in palette (Mulberry) is the app's own default, written by hand in
 * the app blocks; it is listed in the JSON only so the dialog can show it.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(here, "..");
const CSS_PATH = resolve(ROOT, "app", "globals.css");
const PALETTES_PATH = resolve(ROOT, "lib", "theme", "palettes.json");

export const START = "/* theme-accents:start (generated by scripts/theme-accents.mjs; do not edit by hand) */";
export const END = "/* theme-accents:end */";

const SCOPE = ":has([data-app-shell], .vu-admin)";
const BANDS = ":is(.vu-app-sidebar, .vu-admin-rail, .vu-band)";

// ---------------------------------------------------------------- colour math

const toRgb = (hex) => {
  const v = hex.replace("#", "");
  return [0, 2, 4].map((i) => parseInt(v.slice(i, i + 2), 16));
};
const toHex = (rgb) =>
  "#" +
  rgb
    .map((c) => Math.max(0, Math.min(255, Math.round(c))).toString(16).padStart(2, "0"))
    .join("");
const lin = (c) => {
  const v = c / 255;
  return v <= 0.04045 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4;
};
const unlin = (c) => 255 * (c <= 0.0031308 ? c * 12.92 : 1.055 * c ** (1 / 2.4) - 0.055);

export const luminance = (hex) => {
  const [r, g, b] = toRgb(hex).map(lin);
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
};

export const contrast = (a, b) => {
  const [hi, lo] = [luminance(a), luminance(b)].sort((m, n) => n - m);
  return (hi + 0.05) / (lo + 0.05);
};

// OKLab, so a mix keeps its hue instead of greying through sRGB.
const toOklab = (hex) => {
  const [r, g, b] = toRgb(hex).map(lin);
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
  return [
    0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s,
    1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s,
    0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s,
  ];
};
const fromOklab = ([L, a, b]) => {
  const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3;
  return toHex(
    [
      4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
      -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
      -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
    ].map(unlin),
  );
};

/** `amount` of `b` mixed into `a`, in OKLab. */
export const mix = (a, b, amount) => {
  const A = toOklab(a);
  const B = toOklab(b);
  return fromOklab(A.map((v, i) => v + (B[i] - v) * amount));
};

const chroma = (hex) => {
  const [, a, b] = toOklab(hex);
  return Math.hypot(a, b);
};

const WHITE = "#ffffff";
const BLACK = "#000000";

/** Nudge `fg` toward `toward` until it clears `min` against `bg`. */
function clear(fg, bg, min, toward) {
  let out = fg;
  for (let step = 0; step < 80 && contrast(out, bg) < min; step += 1) out = mix(out, toward, 0.06);
  return out;
}

// ------------------------------------------------------------------ the grounds

const CR = String.fromCharCode(13);

/** `--name: #hex;` declarations in the block that opens with `opener`. */
export function tokensIn(css, opener) {
  const at = css.indexOf(opener);
  if (at === -1) throw new Error(`Block not found: ${opener}`);
  const open = css.indexOf("{", at);
  let depth = 0;
  let end = open;
  for (let i = open; i < css.length; i += 1) {
    if (css[i] === "{") depth += 1;
    else if (css[i] === "}") {
      depth -= 1;
      if (depth === 0) {
        end = i;
        break;
      }
    }
  }
  const tokens = {};
  for (const [, name, hex] of css.slice(open, end).matchAll(/--([a-z0-9-]+)\s*:\s*(#[0-9a-fA-F]{6})\s*;/g)) {
    tokens[name] = hex.toLowerCase();
  }
  return tokens;
}

export function readCss() {
  return readFileSync(CSS_PATH, "utf8").split(CR).join("");
}

export function readPalettes() {
  return JSON.parse(readFileSync(PALETTES_PATH, "utf8"));
}

/** The app's light and dark grounds, as `globals.css` declares them. */
export function readBases(css = readCss()) {
  return {
    light: tokensIn(css, `:root${SCOPE} {`),
    dark: { ...tokensIn(css, `:root${SCOPE} {`), ...tokensIn(css, `:root.dark${SCOPE} {`) },
  };
}

// --------------------------------------------------------------- derivation

function lightTokens(swatches, fillIndex, base) {
  const [c1, , c3, c4] = swatches;
  const F = swatches[fillIndex];
  const S = base.surface;
  const brandStrong = clear(mix(F, c1, 0.35), S, 7, BLACK);
  // The palette's light end is the tint chips, badges and the active row sit
  // on. Kept when it reads on the page, by lightness or by hue (Midnight's
  // cream); otherwise a pale tint of the palette's mid colour.
  let wash = chroma(c4) > 0.035 ? c4 : mix(c4, WHITE, 0.25);
  if (contrast(wash, base.background) < 1.06 && chroma(wash) <= 0.035) wash = mix(c3, WHITE, 0.62);
  const fill = clear(F, WHITE, 4.5, BLACK);
  const hover = mix(fill, BLACK, 0.12);
  const tokens = {
    brand: clear(F, S, 3, BLACK),
    "brand-strong": brandStrong,
    "brand-wash": wash,
    "on-brand-wash": clear(c1, wash, 7, BLACK),
    "on-brand": WHITE,
    "brand-fill": fill,
    "brand-fill-hover": hover,
    "brand-fill-foreground": WHITE,
    primary: fill,
    "primary-foreground": WHITE,
    accent: fill,
    "accent-foreground": WHITE,
    focus: brandStrong,
    link: brandStrong,
    highlight: fill,
    "highlight-ink": brandStrong,
    "highlight-wash": wash,
    "on-highlight": WHITE,
    sidebar: c1,
    "sidebar-foreground": WHITE,
    "sidebar-accent": c4,
    "sidebar-accent-foreground": clear(c1, c4, 4.5, BLACK),
    "sidebar-border": mix(c1, BLACK, 0.28),
    "sidebar-ring": WHITE,
    forest: brandStrong,
    "deep-forest": mix(brandStrong, BLACK, 0.2),
    sage: wash,
    "cta-fill": fill,
    "cta-fill-hover": hover,
    "cta-fill-foreground": WHITE,
  };
  const bandFill = clear(mix(c1, WHITE, 0.13), WHITE, 4.5, BLACK);
  const muted = clear(mix(c4, WHITE, 0.35), bandFill, 4.5, WHITE);
  const band = {
    "foreground-muted": muted,
    olive: muted,
    "surface-muted": bandFill,
    default: bandFill,
    border: tokens["sidebar-border"],
    separator: tokens["sidebar-border"],
    "hairline-firm": mix(c1, WHITE, 0.24),
    "brand-fill": WHITE,
    "brand-fill-hover": c4,
    "brand-fill-foreground": clear(c1, c4, 4.5, BLACK),
    "on-highlight": c1,
    sage: c4,
    forest: c1,
  };
  return { tokens, band };
}

function darkTokens(swatches, darkFill, darkInk, base) {
  const [c1, , c3, c4] = swatches;
  const S = base.surface;
  const pick = darkFill === "lift2" ? mix(c3, WHITE, 0.45) : swatches[darkFill];
  const fill = clear(pick, BLACK, 3.2, WHITE);
  const label = clear(c1, fill, 4.5, BLACK);
  // Brand text on black: the fill lifted, or, where the fill is close to the
  // body text's own white (Midnight's cream), the palette's blue lifted, so a
  // link still reads as a link.
  const brandStrong =
    darkInk === undefined
      ? clear(mix(fill, WHITE, 0.25), S, 7, WHITE)
      : clear(mix(swatches[darkInk], WHITE, 0.5), S, 7, WHITE);
  // A dark tint for chips. Midnight's darkest is all but black, so its tint
  // comes from the mid blue instead.
  const wash = luminance(c1) < 0.01 ? mix(c3, BLACK, 0.45) : mix(c1, BLACK, 0.2);
  const sidebar = mix(c1, BLACK, 0.3);
  const hover = mix(fill, WHITE, 0.14);
  const tokens = {
    brand: clear(fill, S, 3, WHITE),
    "brand-strong": brandStrong,
    "brand-wash": wash,
    "on-brand-wash": clear(mix(c4, WHITE, 0.2), wash, 7, WHITE),
    "on-brand": label,
    "brand-fill": fill,
    "brand-fill-hover": hover,
    "brand-fill-foreground": label,
    primary: fill,
    "primary-foreground": label,
    accent: fill,
    "accent-foreground": label,
    focus: brandStrong,
    link: brandStrong,
    highlight: fill,
    "highlight-ink": brandStrong,
    "highlight-wash": wash,
    "on-highlight": label,
    sidebar,
    "sidebar-foreground": WHITE,
    "sidebar-accent": c4,
    "sidebar-accent-foreground": clear(c1, c4, 4.5, BLACK),
    // A rail on a black page needs an edge you can see.
    "sidebar-border": mix(sidebar, WHITE, 0.12),
    "sidebar-ring": WHITE,
    forest: brandStrong,
    "deep-forest": brandStrong,
    sage: wash,
    "cta-fill": fill,
    "cta-fill-hover": hover,
    "cta-fill-foreground": label,
  };
  const bandFill = clear(mix(sidebar, WHITE, 0.12), WHITE, 4.5, BLACK);
  const muted = clear(mix(c4, WHITE, 0.3), bandFill, 4.5, WHITE);
  const band = {
    "foreground-muted": muted,
    olive: muted,
    "surface-muted": bandFill,
    default: bandFill,
    border: tokens["sidebar-border"],
    separator: tokens["sidebar-border"],
    "hairline-firm": mix(sidebar, WHITE, 0.22),
    "brand-fill": WHITE,
    "brand-fill-hover": c4,
    "brand-fill-foreground": clear(c1, c4, 4.5, BLACK),
    "on-highlight": c1,
    sage: c4,
    forest: c1,
  };
  return { tokens, band };
}

/** A palette's four token sets: light, dark, and the band in each. */
export function derivePalette(palette, bases) {
  return {
    light: lightTokens(palette.swatches, palette.fill, bases.light),
    dark: darkTokens(palette.swatches, palette.darkFill, palette.darkInk, bases.dark),
  };
}

// ---------------------------------------------------------------- contrast

/** What each palette must clear, in each mode. Mirrors check-theme-contrast. */
export const ACCENT_PAIRS = [
  ["brand-strong", "surface", 4.5],
  ["on-brand-wash", "brand-wash", 4.5],
  ["brand", "surface", 3],
  ["brand-fill-foreground", "brand-fill", 4.5],
  ["link", "surface", 4.5],
  ["focus", "surface", 3],
  ["brand-fill", "background", 3],
  ["highlight-ink", "surface", 4.5],
  ["highlight-ink", "highlight-wash", 4.5],
  ["on-highlight", "highlight", 4.5],
  ["highlight-ink", "background", 4.5],
  ["sidebar-foreground", "sidebar", 4.5],
  ["sidebar-accent-foreground", "sidebar-accent", 4.5],
];

export const ACCENT_BAND_PAIRS = [
  ["foreground", "sidebar", 4.5],
  ["foreground-muted", "sidebar", 4.5],
  ["foreground", "surface-muted", 4.5],
  ["foreground-muted", "surface-muted", 4.5],
  ["brand-fill-foreground", "brand-fill", 4.5],
  ["brand", "sidebar", 3],
  ["sidebar-accent-foreground", "sidebar-accent", 4.5],
];

/** Every failing pair, as readable lines. Empty when the palette passes. */
export function failures(id, derived, bases) {
  const out = [];
  for (const mode of ["light", "dark"]) {
    const scope = { ...bases[mode], ...derived[mode].tokens };
    const band = { ...scope, foreground: WHITE, brand: WHITE, ...derived[mode].band };
    for (const [fg, bg, min] of ACCENT_PAIRS) {
      const r = contrast(scope[fg], scope[bg]);
      if (r < min) out.push(`${id} ${mode}: ${fg} on ${bg} is ${r.toFixed(2)}:1 (needs ${min})`);
    }
    for (const [fg, bg, min] of ACCENT_BAND_PAIRS) {
      const r = contrast(band[fg], band[bg]);
      if (r < min) out.push(`${id} ${mode} band: ${fg} on ${bg} is ${r.toFixed(2)}:1 (needs ${min})`);
    }
  }
  return out;
}

// ------------------------------------------------------------------ the CSS

const declarations = (tokens) =>
  Object.entries(tokens)
    .map(([name, value]) => `  --${name}: ${value};`)
    .join("\n");

export function renderAccents(palettes, bases) {
  const parts = [START];
  for (const palette of palettes.filter((p) => !p.builtin)) {
    const derived = derivePalette(palette, bases);
    const id = palette.id;
    parts.push(
      "",
      `/* ${palette.name}: ${palette.swatches.join(" ")} */`,
      `:root[data-accent="${id}"]${SCOPE} {\n${declarations(derived.light.tokens)}\n}`,
      `:root.dark[data-accent="${id}"]${SCOPE} {\n${declarations(derived.dark.tokens)}\n}`,
      `:root[data-accent="${id}"]${SCOPE} ${BANDS} {\n${declarations(derived.light.band)}\n}`,
      `:root.dark[data-accent="${id}"]${SCOPE} ${BANDS} {\n${declarations(derived.dark.band)}\n}`,
    );
  }
  parts.push("", END);
  return parts.join("\n");
}

/** The stylesheet with its accent block replaced by `block`. */
export function withAccents(css, block) {
  const start = css.indexOf(START);
  const end = css.indexOf(END);
  if (start === -1 || end === -1 || end < start) {
    throw new Error("theme-accents markers not found in app/globals.css");
  }
  return css.slice(0, start) + block + css.slice(end + END.length);
}

// --------------------------------------------------------------------- main

function main() {
  const check = process.argv.includes("--check");
  const raw = readFileSync(CSS_PATH, "utf8");
  const crlf = raw.includes(CR + "\n");
  const css = raw.split(CR).join("");
  const bases = readBases(css);
  const { palettes } = readPalettes();

  const problems = palettes
    .filter((p) => !p.builtin)
    .flatMap((p) => failures(p.id, derivePalette(p, bases), bases));
  if (problems.length) {
    console.error(problems.join("\n"));
    console.error(`${problems.length} pair(s) fail; nothing written.`);
    process.exit(1);
  }

  const next = withAccents(css, renderAccents(palettes, bases));
  if (check) {
    if (next !== css) {
      console.error("app/globals.css is out of date: run node scripts/theme-accents.mjs");
      process.exit(1);
    }
    console.log("theme accents are up to date");
    return;
  }
  writeFileSync(CSS_PATH, crlf ? next.split("\n").join(CR + "\n") : next);
  console.log(`wrote ${palettes.filter((p) => !p.builtin).length} accents into app/globals.css`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
